### PR TITLE
add context.FieldsWith

### PR DESCRIPTION
**Pull request by exherb**

### CODE REVIEW

**Comment by rs** [comment]
I don’t see a use-case for that. Can you give one?

**Comment by exherb** [comment]
some log system like graylog use _ as special mark https://docs.graylog.org/en/3.1/pages/gelf.html

**Comment by rs** [comment]
I'm not sure it is the role of the log library to add those. It' easy enough to do that in your app.

**Comment by exherb** [comment]
then chain is not possible …

**Comment by rs** [comment]
How about that?

```go
func fieldsPrefix(fields map[string]interface{}, prefix string) map[string]interface{} {
 	r := make(map[string]interface{}, len(fields))
 	for k, v := range fields {
 		r[strings.Join([]string{prefix, k}, "")] = v
 	}
 	return r
 }

log.Info().Fields(fieldsPerfix(someFields, "_")).Msg("Hello")
```

**Comment by exherb** [comment]
ok, thanks.

**Pull request closed without merging**
