### PR TITLE
Implement the encoding.TextUnmarshaler interface for log level.

### PR DESCRIPTION
**Pull request by Kirguir**
Implement the encoding.TextUnmarshaler interface for log level from its string representation.

### CODE REVIEW

**Comment by rs** [comment]
Sorry for the delay, I missed this PR.

What's the use case for this?

**Comment by rs** [comment]
Might be dup of #48

**Comment by rs** [comment]
Fixed by #57

**Comment by maroux** [comment]
Hm, just ran into this as well. `ParseLevel` is a custom method that needs to be called. Implementing `TextUnmarshaler` would let other libraries (e.g. https://github.com/BurntSushi/toml) unmarshal log level automatically based on that stdlib interface.

**Comment by maroux** [comment]
Just opened a PR, we can discuss further there :)

**Pull request closed without merging**
