### PR TITLE
Add the concept of per-category log level

### PR DESCRIPTION
**Pull request by arl**

### CODE REVIEW

**Comment by rs** [comment]
Does not look like a PR that was meant to be upstreamed. If yes, please reoopen, add a description explaining what you are trying to solve, and remove s/rs/arl/.

**Comment by arl** [comment]
That's correct, that was not meant to be upstreamed and was opened on the
wrong remote. Sorry for the noise

**Comment by xmlking** [comment]
@arl ability to configure  per-category log level  will be useful for many use-cases ( in case if I want to enable debug level logs only for a specific module in prod) 
Wonder if you contribute back  to zerolog
Thanks

**Comment by arl** [comment]
@xmlking yes that's the idea: being able to assign a category to log events and manage levels on a per-category basis.

The implementation I have aims at having a close-to-zero runtime cost, but it adds a 1-byte field to the Event `struct` to store the category, allowing up to 256 categories, which should be more than enough.

Most of the code is in https://github.com/arl/zerolog/commit/0de11d925f64a50ba7ac70bb364f2d71d0adcc2e I can clean that up a bit and open a PR if that's of interest to the maintainers.

**Comment by xmlking** [comment]
thanks a lot @arl . looking for exactly that to control logging per category with config.yaml or environmental variables, in production

**Pull request closed without merging**
