### PR TITLE
Allow user to custom order of field in ConsoleWriter

### PR DESCRIPTION
**Pull request by TommyCpp**
As point out in #155. It would be nice to have some control on the order of the output field.

Add example on how to custom field's order.

### CODE REVIEW

**Comment by toni-moreno** [comment]
:+1

**Comment by BK-Choi** [comment]
@TommyCpp is there any news?

**Comment by TommyCpp** [comment]
> @TommyCpp is there any news?

I don’t think it’s gonna be merged. Haven’t heard from the author.

**Comment by BenjamenMeyer** [comment]
Nice; it would be great if there was a default implementation that ordered by the JSON/Dict keys as that would probably be the most common sort method.

**Comment by vidhanio** [comment]
Any updates on this feature? This would be very helpful. :)

**Comment by madkins23** [comment]
Just submitted PR #550. Should have checked for previous work first.  :-(

**Comment by lammel** [comment]
@rs This can probably be closed as PR #550 is merged now.

**Pull request closed without merging**
