### PR TITLE
Release a new GitHub Releases automatically when a Tag is pushed

### LINKED ISSUE #421: Public release and tagging
When you go on the repository page, you can see that there is only one release : v1.0.0 on 23 June 2017

This can make think a lot of people that zerolog is an old and not very active project, but if we take a look we can really see how active is the project. Almost on tag per month !

It might be a good thing to automatically create release on tag with GitHub workflow

### PR DESCRIPTION
**Pull request by GalvinGao**
This PR fixes #421

### CODE REVIEW

**Comment by yogi1990** [comment]
@rs Can you review and merge this PR. This is something we are eagerly looking for it.

**Comment by rs** [comment]
Why do you need github releases?

**Comment by yogi1990** [comment]
@rs the github release definitely gives confidence while evaluating logging/ any package that package is well maintained by community / contributors.  Ideally tags created is enough from technically point of view. But not publishing github release adds some questions on maintainability of package and hiccups in consuming same.

Request is to manually publish github release for now. That will help a lot.

**Comment by rs** [comment]
Well, if there is no actual requirement for gh release, I will stay with simple tags, it’s good enough.

**Comment by kittydoor** [comment]
On top of making releases more visually accessible at first sight (especially when there is existing releases already), they also make it easier to stremline checking software versions across a variety of technologies without having to specially filter for this uses tags, that uses dockerhub, etc etc. They would be very helpful and appreciated.

**Pull request closed without merging**
