### PR TITLE
FilteredLevelWriter writes only logs at Level or above

### LINKED ISSUE #150: Multiple writers, different levels on each?
Hi,

I'm trying to configure zerolog to output logs both to the console and a file, with different formats. I can easily do that with `ConsoleWriter` and `io.MultiWriter`.

But I'm also trying to have the different log destinations log different levels.

I couldn't find a way do it. I tried to see if a Hook would solve it, but apparently the hooks seem to apply before the logs are sent to the Writers.

Is there a way to do it?

Thanks

### PR DESCRIPTION
**Pull request by mitar**
Fixes #150.

This allows one to combine `FilteredLevelWriter`, `LevelWriterAdapter` and `MultiLevelWriter` into any way you want. E.g., have info and above being logged to the console while all levels to a file.

### CODE REVIEW

**Comment by mitar** [comment]
Maybe it should be named `FilteredLevelWriter`. I will push this right now.

**Comment by rs** [comment]
The recommended way to do that is to set the level on the logger, so the event is skipped early.

**Comment by mitar** [comment]
> The recommended way to do that is to set the level on the logger, so the event is skipped early.

Yes, but this is not possible if you want to log to multiple destinations (e.g., console and file). Then you have to set the level on the logger to the lowest of those you want and then filter at the writer.

**Comment by rs** [comment]
Make sense. Can you please add a note on the description of this writer about the use-case it is covering so people don’t think that is the recommended way to deal with levels?

**Comment by mitar** [comment]
Done!

**Pull request merged**
